### ISSUE TITLE
可以上传一个workflow.json吗，版本好像有很多冲突

### ISSUE THREAD

**Issue by nothairyyq** [smthemex/ComfyUI_Hallo2#17]
1. hallo2是不是有很多版本以来的冲突，torchaudio我已经重新装了，huggingface hub也降低了版本。
2. workflow跑到HalloUpscale的时候说我模型或者torch版本有问题，可以帮忙看看吗
: 
Traceback (most recent call last):
  File "/workspace/lawks/ComfyUI/execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/workspace/lawks/ComfyUI/execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/workspace/lawks/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/workspace/lawks/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/workspace/lawks/ComfyUI/custom_nodes/ComfyUI_Hallo2/Hallo_node.py", line 618, in Upscale_main
    net,face_upsampler,bg_upsampler,face_helper=pre_u_loader(bg_upsampler, model_path, bg_tile, upscale, face_upsample, device, hallo_model_path,face_detection_model,parse_model,has_aligned)
  File "/workspace/lawks/ComfyUI/custom_nodes/ComfyUI_Hallo2/hallo/video_sr.py", line 95, in pre_u_loader
    raise "un support torch version or checkpoints"
TypeError: exceptions must derive from BaseException

![Snipaste_2024-12-17_11-25-39](https://github.com/user-attachments/assets/39a3180c-d3fe-400b-8d45-75d5ed44bb0f)

**Comment by smthemex** [comment]
![image](https://github.com/user-attachments/assets/1b9a5411-f827-4f81-9e4a-6542b547c824)
我看了一下这行代码的报错，是net_g.pth 这个模型的问题，你重新下载一个试试，而且这个的确跟torch版本有关系，代码是涵盖了不同版本的torch加载的

**Comment by nothairyyq** [comment]
非常感谢您的回答，我的torch相关版本是:
torch                              2.2.2
torchaudio                         2.2.2
torchsde                           0.2.6
torchvision                        0.17.2

重新下载了net_g,发现还是有新的报错，也出现在HallosUpscaleloader node上。报错信息如下：
!!! Exception during processing !!! invalid load key, 'v'.
Traceback (most recent call last):
  File "/workspace/lawks/ComfyUI/execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/workspace/lawks/ComfyUI/execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/workspace/lawks/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/workspace/lawks/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/workspace/lawks/ComfyUI/custom_nodes/ComfyUI_Hallo2/Hallo_node.py", line 618, in Upscale_main
    net,face_upsampler,bg_upsampler,face_helper=pre_u_loader(bg_upsampler, model_path, bg_tile, upscale, face_upsample, device, hallo_model_path,face_detection_model,parse_model,has_aligned)
  File "/workspace/lawks/ComfyUI/custom_nodes/ComfyUI_Hallo2/hallo/video_sr.py", line 117, in pre_u_loader
    face_helper = FaceRestoreHelper(
  File "/workspace/lawks/ComfyUI/custom_nodes/ComfyUI_Hallo2/hallo/facelib/utils/face_restoration_helper.py", line 125, in __init__
    self.face_detector = init_detection_model(self.det_model, half=False, device=self.device)
  File "/workspace/lawks/ComfyUI/custom_nodes/ComfyUI_Hallo2/hallo/facelib/detection/__init__.py", line 16, in init_detection_model
    model = init_retinaface_model(model_name, half, device)
  File "/workspace/lawks/ComfyUI/custom_nodes/ComfyUI_Hallo2/hallo/facelib/detection/__init__.py", line 37, in init_retinaface_model
    load_net = torch.load(model_name, map_location=lambda storage, loc: storage)
  File "/workspace/hallo/lib/python3.10/site-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/workspace/hallo/lib/python3.10/site-packages/torch/serialization.py", line 1258, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

非常感谢您宝贵的时间

**Comment by smthemex** [comment]
检查一下你的accelerate的版本，官方的要求accelerate==0.28.0

**Comment by nothairyyq** [comment]
依旧是跑到HallosVideoUpscale有问题，前面的应该都推理完了。warning信息：Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference. 感觉还是某些模型文件或者什么库的版本有问题，我的accelerate就是0.28.0

**Comment by smthemex** [comment]
你是Linux跑的吗? 你把[这行](https://github.com/smthemex/ComfyUI_Hallo2/blob/main/Hallo_node.py#L546) 注释掉，这是为了小显存做的模型卸载，可能你那里不支持。

**Comment by nothairyyq** [comment]
嗯嗯好的非常感谢，我尝试一下，我用的A40 40G的显存
