### ISSUE TITLE
HalloPreImgAndAudio  [WinError 2] The system cannot find the file specified solution?

### ISSUE THREAD

**Issue by fusillustrator** [smthemex/ComfyUI_Hallo2#21]
![assaasasas](https://github.com/user-attachments/assets/227344c6-4db1-408a-a986-08fc9a577493)

# ComfyUI Error Report
## Error Details
- **Node ID:** 3
- **Node Type:** HalloPreImgAndAudio
- **Exception Type:** FileNotFoundError
- **Exception Message:** [WinError 2] The system cannot find the file specified
## Stack Trace
```
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Hallo2\Hallo_node.py", line 321, in loader_main
    audio_embs, audio_length = load_audio(use_cut, driving_audio_file, save_path, sample_rate, fps,
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Hallo2\Hallo_node.py", line 110, in load_audio
    audio_list = cut_audio(driving_audio_file,save_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Hallo2\scripts\inference_long.py", line 143, in cut_audio
    audio = AudioSegment.from_wav(audio_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pydub\audio_segment.py", line 808, in from_wav
    return cls.from_file(file, 'wav', parameters=parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "subprocess.py", line 1026, in __init__

  File "subprocess.py", line 1538, in _execute_child

```
## System Information
- **ComfyUI Version:** v0.3.7-42-gf4cdedea
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.5.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 12884377600
  - **VRAM Free:** 10428839970
  - **Torch VRAM Total:** 771751936
  - **Torch VRAM Free:** 18577442

## Logs
```
2024-12-22T15:53:21.030346 -  2024-12-22T15:53:21.030346 - ['None', 3, 112, 112]2024-12-22T15:53:21.030346 -  2024-12-22T15:53:21.030346 - 127.52024-12-22T15:53:21.030346 -  2024-12-22T15:53:21.030346 - 127.52024-12-22T15:53:21.030346 - 
2024-12-22T15:53:21.064870 - Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'device_id': '0', 'has_user_compute_stream': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'user_compute_stream': '0', 'gpu_external_alloc': '0', 'gpu_mem_limit': '18446744073709551615', 'enable_cuda_graph': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'do_copy_in_default_stream': '1', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0', 'prefer_nhwc': '0', 'use_ep_level_unified_stream': '0', 'use_tf32': '1', 'sdpa_kernel': '0', 'fuse_conv_bias': '0'}, 'CPUExecutionProvider': {}}2024-12-22T15:53:21.065870 - 
2024-12-22T15:53:21.065870 - find model:2024-12-22T15:53:21.065870 -  2024-12-22T15:53:21.066374 - D:\ComfyUI_windows_portable\ComfyUI\models\Hallo\face_analysis\models\scrfd_10g_bnkps.onnx2024-12-22T15:53:21.066374 -  2024-12-22T15:53:21.066374 - detection2024-12-22T15:53:21.066374 -  2024-12-22T15:53:21.066374 - [1, 3, '?', '?']2024-12-22T15:53:21.066374 -  2024-12-22T15:53:21.066374 - 127.52024-12-22T15:53:21.066374 -  2024-12-22T15:53:21.066374 - 128.02024-12-22T15:53:21.067378 - 
2024-12-22T15:53:21.067378 - set det-size:2024-12-22T15:53:21.067378 -  2024-12-22T15:53:21.068380 - (640, 640)2024-12-22T15:53:21.069382 - 
2024-12-22T15:53:21.441066 - Processed and saved: D:\ComfyUI_windows_portable\ComfyUI\output\temp_575974_sep_background.png2024-12-22T15:53:21.441066 - 
2024-12-22T15:53:21.442066 - Processed and saved: D:\ComfyUI_windows_portable\ComfyUI\output\temp_575974_sep_face.png2024-12-22T15:53:21.442066 - 
2024-12-22T15:53:21.510853 - img processing is done2024-12-22T15:53:21.510853 - 
2024-12-22T15:53:21.522248 - pre radio processing2024-12-22T15:53:21.522248 - 
2024-12-22T15:53:21.530753 - !!! Exception during processing !!! [WinError 2] The system cannot find the file specified
2024-12-22T15:53:21.531754 - Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Hallo2\Hallo_node.py", line 321, in loader_main
    audio_embs, audio_length = load_audio(use_cut, driving_audio_file, save_path, sample_rate, fps,
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Hallo2\Hallo_node.py", line 110, in load_audio
    audio_list = cut_audio(driving_audio_file,save_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Hallo2\scripts\inference_long.py", line 143, in cut_audio
    audio = AudioSegment.from_wav(audio_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pydub\audio_segment.py", line 808, in from_wav
    return cls.from_file(file, 'wav', parameters=parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "subprocess.py", line 1026, in __init__
  File "subprocess.py", line 1538, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

2024-12-22T15:53:21.532753 - Prompt executed in 1.32 seconds

**Comment by smthemex** [comment]
check your ffmpeg
